[package]
name = "todoapp"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.140"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.38", features = ["derive"] }
shlex = "1.3"
